### ISSUE TITLE
Automount USB drive inserted 

### ISSUE THREAD

**Issue by peterdcrees** [mountainhazelnuts/Met-station#1]
Goal: Keep a copy of the met data on a USB stick that can be collected by field staff without a laptop.

On insert of ANY USB thumb drive (4-8GB FAT32) the drive should be automatically mounted RW at a location that can be found and written to by a daily data backup script.

Also unmount mount points for unplugged drives

**Comment by peterdcrees** [comment]
@swangchuckmh
Try: https://www.raspberrypi.org/forums/viewtopic.php?t=192291#p1211152

**Comment by swangchukmh** [comment]
@peterdcrees  still not working.

**Comment by swangchukmh** [comment]
@peterdcrees @brunosan   Did this but still didnt worked.

Installed pmount
sudo apt-get install pmount

Created file /etc/udev/rules.d/usbstick.rules

ACTION=="add", KERNEL=="sd[a-z][0-9]", TAG+="systemd", ENV{SYSTEMD_WANTS}="usbstick-handler@%k"

Save and close

Systemd service

Created file /lib/systemd/system/usbstick-handler@.service

[Unit]
Description=Mount USB sticks
BindsTo=dev-%i.device
After=dev-%i.device

[Service]

Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/local/bin/cpmount /dev/%I
ExecStop=/usr/bin/pumount /dev/%I

Save and close

Mount script

Create file /usr/local/bin/cpmount
Insert:
#!/bin/bash
if mountpoint -q /media/usb1
then
   if mountpoint -q /media/usb2
   then
      if mountpoint -q /media/usb3
      then
         if mointpoint -1 /media/usb4
         then
             echo "No mountpoints available!"
             #You can add more if you need
         else
             /usr/bin/pmount --umask 00 -noatime -r --sync $1 usb4
         fi
      else
         /usr/bin/pmount --umask 000 --noatime -r --sync $1 usb3
      fi
   else
      /usr/bin/pmount --umask 000 --noatime -r --sync $1 usb2
   fi
else
   /usr/bin/pmount --umask 000 --noatime -r --sync $1 usb1
fi

Save and close

Finish

**Comment by peterdcrees** [comment]
Suggest we see how it is done on the full GUI version of Raspbian Stretch with desktop 
https://www.raspberrypi.org/downloads/raspbian/

**Comment by peterdcrees** [comment]
Automount on Raspbian lite needs the udisks2 package to be installed

`sudo apt install udisks2`

Enable udisks2 service

`sudo systemctl enable udisks2`
